INSERT INTO VEICULO (ID_VEICULO, TIPO_VEICULO, MARCA_VEICULO, ANO_VEICULO, MODELO_VEICULO, COR_VEICULO, VELOCIDADE_MAX_VEICULO, QUILOMETRAGEM_VEICULO)
VALUES (1, 'PATINETE', 'Importway', 2018, 'BW-008', 'Preto', '12km/h', '500km');
INSERT INTO VEICULO (ID_VEICULO, TIPO_VEICULO, MARCA_VEICULO, ANO_VEICULO, MODELO_VEICULO, COR_VEICULO, VELOCIDADE_MAX_VEICULO, QUILOMETRAGEM_VEICULO)
VALUES (2, 'PATINETE', 'Freego', 2017, 'ESO6C', 'Preto', '24km/h', '1000km');
INSERT INTO VEICULO (ID_VEICULO, TIPO_VEICULO, MARCA_VEICULO, ANO_VEICULO, MODELO_VEICULO, COR_VEICULO, VELOCIDADE_MAX_VEICULO, QUILOMETRAGEM_VEICULO)
VALUES (3, 'BICICLETA', 'Caloi', 2019, 'Montana Mountain Bike', 'Preto', NULL, '200km');

INSERT INTO CONDUTOR (CPF_CONDUTOR, NOME_CONDUTOR, EMAIL_CONDUTOR)
VALUES (55567770049, 'CondutorTeste', 'condutor@teste.com');
