CREATE TABLE VEICULO(
    ID_VEICULO NUMBER(10) NOT NULL,
    TIPO_VEICULO VARCHAR2(20) NOT NULL,
    MARCA_VEICULO VARCHAR2(50) NOT NULL,
    ANO_VEICULO NUMBER(4) DEFAULT NULL,
    MODELO_VEICULO VARCHAR(50) DEFAULT NULL,
    COR_VEICULO VARCHAR(50) DEFAULT NULL,
    VELOCIDADE_MAX_VEICULO VARCHAR(10) DEFAULT NULL,
    QUILOMETRAGEM_VEICULO VARCHAR(10) DEFAULT NULL,
    ULTIMA_CORRIDA_VEICULO VARCHAR2(20) DEFAULT NULL
);

CREATE TABLE CONDUTOR(
    CPF_CONDUTOR NUMBER(11) NOT NULL,
    NOME_CONDUTOR VARCHAR2(50) DEFAULT NULL,
    EMAIL_CONDUTOR VARCHAR2(50) DEFAULT NULL,
    SALDO_CONDUTOR DOUBLE DEFAULT 0,
);

CREATE TABLE ALUGUEL(
    ID_ALUGUEL NUMBER(10) NOT NULL,
    ID_VEICULO NUMBER(10) NOT NULL,
    PRECO DOUBLE DEFAULT 0,
    EMAIL_CONDUTOR VARCHAR2(50) NOT NULL,
    DATA_INICIO_ALUGUEL VARCHAR2(20) DEFAULT NULL,
    DATA_FIM_ALUGUEL VARCHAR2(20) DEFAULT NULL
);